### ISSUE TITLE
NOT WORKING!

### ISSUE THREAD

**Issue by dragon-stark** [svipas/vscode-prettier-plus#11]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by svipas** [comment]
Could please elaborate more? Because it works for me and others. If it doesn't work please say which VS Code language id you're using, file extension, content if possible and output of Prettier which can be found in `Output` panel in dropdown select `Prettier+`.

I'm closing this issue for now, after you gather all the needed info please re-open it.

/cc @dragon-stark
