### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by lodestarSoft-Eh** [svipas/vscode-prettier-plus#19]
- Issue Type: `Bug`
- Extension Name: `prettier-plus`
- Extension Version: `3.6.6`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by svipas** [comment]
Hi, could you please give me the output of that log file you forgot to include? Also, I'm right now upgrading Prettier version and making few changes so maybe your problem would be fixed in the next release. I'm closing issue, if you think problem will exist even after new released version of extension, please re-open it.
